language: node_js

node_js:
  - '4'

branches:
  only:
    - master
    - "/^v[0-9\\.]+$"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm prune

install:
  - npm install
  - node_modules/.bin/bower install
  - node_modules/.bin/bower prune

script:
  - node_modules/.bin/gulp karma:ci

after_success:
  - coveralls
