language: node_js

node_js:
  - '4'

branches:
  only:
    - master

sudo: false

env:
  - BUILD=static-no-linting
  - BUILD=static-only-linting

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm prune

install:
  - npm install
  - node_modules/.bin/bower install
  - node_modules/.bin/bower prune

script:
  - ci-scripts/script.sh

after_success:
  - ci-scripts/after-success.sh
